name: Notebook CI/CD to Databricks

on:
  push:
    branches:
      - dev
      - qa
      - prod
      - main
    paths:
      - notebooks/hello.ipynb

jobs:
  promote-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install required tools
        run: |
          python -m pip install --upgrade pip
          pip install requests databricks-cli

      - name: Determine Databricks folder
        id: target
        run: |
          case "${{ github.ref_name }}" in
            dev)   folder="/Repos/sunainag4444@gmail.com/github-actions-ci-cd-dev" ;;
            qa)    folder="/Repos/sunainag4444@gmail.com/github-actions-ci-cd-qa" ;;
            prod)  folder="/Repos/sunainag4444@gmail.com/github-actions-ci-cd-prod" ;;
            main)  folder="/Repos/sunainag4444@gmail.com/github-actions-ci-cd" ;;
            *)     echo "Unsupported branch"; exit 1 ;;
          esac
          echo "folder=$folder" >> $GITHUB_OUTPUT

      - name: Upload notebook to Databricks
        run: |
          folder="${{ steps.target.outputs.folder }}"
          echo "Uploading to Databricks folder: $folder"

          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import" \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -F path="$folder/hello" \
            -F format=SOURCE \
            -F language=PYTHON \
            -F overwrite=true \
            -F content=@notebooks/hello.ipynb

      - name: Promote to next GitHub branch (if not main)
        if: ${{ github.ref_name != 'main' }}
        run: |
          case "${{ github.ref_name }}" in
            dev)   next="qa" ;;
            qa)    next="prod" ;;
            prod)  next="main" ;;
            *)     echo "No promotion needed"; exit 0 ;;
          esac

          echo "Promoting notebooks/hello.ipynb to $next"
          git fetch origin
          git checkout $next
          git checkout ${{ github.ref_name }} -- notebooks/hello.ipynb
          git add notebooks/hello.ipynb
          git commit -m "Auto-promoted from ${{ github.ref_name }} to $next"
          git push origin $next
