name: Unified Notebook CI/CD

on:
  push:
    branches:
      - dev
      - qa
      - prod
      - main
    paths:
      - notebooks/hello.ipynb

jobs:
  promote-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests databricks-cli

      - name: Upload notebook to Databricks
        run: |
          # Map branch to Databricks folder
          case "${{ github.ref_name }}" in
            dev)   folder="/github-actions-ci-cd-dev" ;;
            qa)    folder="/github-actions-ci-cd-qa" ;;
            prod)  folder="/github-actions-ci-cd-prod" ;;
            main)  folder="/github-actions-ci-cd" ;;
            *)     echo "Unsupported branch"; exit 1 ;;
          esac

          echo "Uploading to Databricks folder: $folder"

          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import" \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -F path="$folder/hello" \
            -F format=SOURCE \
            -F language=PYTHON \
            -F overwrite=true \
            -F content=@notebooks/hello.ipynb

      - name: Promote to next branch (if applicable)
        if: ${{ github.ref_name != 'main' }}
        run: |
          case "${{ github.ref_name }}" in
            dev)   next="qa" ;;
            qa)    next="prod" ;;
            prod)  next="main" ;;
            *)     echo "No further promotion"; exit 0 ;;
          esac

          git fetch origin
          git checkout $next
          git checkout ${{ github.ref_name }} -- notebooks/hello.ipynb
          git add notebooks/hello.ipynb
          git commit -m "Auto-promoted from ${{ github.ref_name }} to $next"
          git push origin $next
