name: Push to Databricks Main

on:
  push:
    branches:
      - main
    paths:
      - notebooks/hello.ipynb

jobs:
  push-to-main-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests databricks-cli

      # Optional: Configure Databricks CLI (not required for basic curl usage)
      # - name: Configure Databricks CLI
      #   run: |
      #     databricks configure --token << EOF
      #     ${{ secrets.DATABRICKS_HOST }}
      #     ${{ secrets.DATABRICKS_TOKEN }}
      #     EOF

      - name: Push notebook to Databricks /main
        run: |
          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import" \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -F path="/main/hello" \
            -F format=SOURCE \
            -F language=PYTHON \
            -F overwrite=true \
            -F content=@notebooks/hello.ipynb
