name: PR-Based Notebook CI/CD

on:
  pull_request:
    branches:
      - dev
      - qa
      - prod
      - main
    paths:
      - notebooks/hello.ipynb

  # Optional: Still respond to direct pushes if needed
  push:
    branches:
      - dev
      - qa
      - prod
      - main
    paths:
      - notebooks/hello.ipynb

jobs:
  promote-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests databricks-cli

      - name: Determine target folder
        id: target
        run: |
          case "${{ github.base_ref || github.ref_name }}" in
            dev)   folder="/github-actions-ci-cd-dev" ;;
            qa)    folder="/github-actions-ci-cd-qa" ;;
            prod)  folder="/github-actions-ci-cd-prod" ;;
            main)  folder="/github-actions-ci-cd" ;;
            *)     echo "Unsupported branch"; exit 1 ;;
          esac
          echo "folder=$folder" >> $GITHUB_OUTPUT

      - name: Upload notebook to Databricks
        run: |
          folder="${{ steps.target.outputs.folder }}"
          echo "Uploading notebook to Databricks folder: $folder"

          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import" \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -F path="$folder/hello" \
            -F format=SOURCE \
            -F language=PYTHON \
            -F overwrite=true \
            -F content=@notebooks/hello.ipynb
